<a href="https://colab.research.google.com/github/pgm1120/test_project_3/blob/main/lesson_01_contents_orientation_%26_numpy_1_array%2C_zero%2C_one.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 목차
    - numpy
    - pandas
    - matplotlib & seaborn
    - scikit-learn

### Numpy
    - 행렬 연산을 가능하게 해주는 패키지
    - python으로 작성되나 연산은 C, C++, 포트란으로 진행
        - 선형대수 연산을 빠르게 할 수 있음

In [3]:
import numpy as np
ary = np.array([1, 2, 3])
type(ary), ary

(numpy.ndarray, array([1, 2, 3]))

    - ndarray : 한가지 데이터 타입만으로 사용이 가능

In [4]:
ary2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(ary2)
print(ary2.ndim)
print(ary2.shape)
print(ary2.size)
print(ary2.dtype)
ary2, ary2.ndim, ary2.shape

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


(array([[1, 2, 3],
        [4, 5, 6]]), 2, (2, 3))

In [ ]:
ary2.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
ary2[1]

array([4, 5, 6])

In [ ]:
ary2[1, 1]

5

#### 데이터 수정

In [ ]:
ls = [1, 2, 3]
ls[1] = 5
ls

[1, 5, 3]

In [ ]:
ary3 = np.array([[1, 2, 3],
                 [0, 1, 0]])
ary3[1][1] = 0
ary3

array([[1, 2, 3],
       [0, 0, 0]])

##### array 브로드캐스팅

In [ ]:
ary3[0] = 0
ary3

array([[0, 0, 0],
       [0, 0, 0]])

##### array 조건 선택

In [ ]:
ary3[0] = 5
ary3[1] = [5, 6, 7]
ary3

array([[5, 5, 5],
       [5, 6, 7]])

In [ ]:
idx = ary3>5
idx

array([[False, False, False],
       [False,  True,  True]])

In [ ]:
ary3[idx]

array([6, 7])

##### 조건에 맞는 값만 변경

In [ ]:
ary3[idx] = 100
ary3

array([[  5,   5,   5],
       [  5, 100, 100]])

#### zero array

In [ ]:
zero_ary = np.zeros((2, 3))
zero_ary

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
type(zero_ary)

numpy.ndarray

In [ ]:
zero_ary.dtype # 실수형 값만 바꿔 넣을 수 있음

dtype('float64')

##### array안의 데이터 형태 변경

In [ ]:
z2 = zero_ary.astype('int')
z2.dtype

dtype('int32')

#### one array

In [ ]:
one_ary = np.ones((2, 3))
one_ary.dtype, one_ary

(dtype('float64'),
 array([[1., 1., 1.],
        [1., 1., 1.]]))

In [ ]:
one_ary2 = np.ones((2, 3, 2)).astype('int')
one_ary2.dtype, one_ary2

(dtype('int32'),
 array([[[1, 1],
         [1, 1],
         [1, 1]],
 
        [[1, 1],
         [1, 1],
         [1, 1]]]))

#### 범위값 array 생성

In [ ]:
arg = np.arange(1, 11)
arg

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])